server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:postgresql://localhost:5432/my_db_2
      username: my_user
      password: 1234

  ## Email settings
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: leekyung1111@gmail.com
    password: 
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  messages:
    basename: messages.i18n.error
    encoding: UTF-8

# mybatis config
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

# oAuth2 config
oauth2:
  kakao:
    api-key: 803bba301ece0ff0621c3e274fe8e6b2
    authorizaion-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: http://localhost:8080/auth/kakao/callback
  naver:
    api-key: bQI9RwpG4sp4afTMjGx1
    client-secret: OBB3Bho1QS
    authorizaion-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    redirect-uri: http://localhost:8080/auth/naver/callback
  google:
    api-key: 803bba301ece0ff0621c3e274fe8e6b2
    client-secret: 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
    authorizaion-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/drive/v2/files
    redirect-uri: http://localhost:8080/auth/google/callback

